name: nnpf_gpu
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - jupyter
  - pytorch>=1.7.0,<=1.8.1
  - torchvision>=0.8.1
  - cudatoolkit=10.2
  - pytorch-lightning=1.2.9
  - tqdm
  - imageio
  - imageio-ffmpeg
  - pytest
