name: nnpf_cpu
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - jupyter
  - pytorch=1.6.0
  - torchvision>=0.7.0
  - cpuonly
  - pytorch-lightning=1.0.8
  - tqdm
  - imageio
  - imageio-ffmpeg
  - pytest
