name: nnpf_gpu
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python >= 3.8
  - numpy
  - matplotlib
  - jupyter
  - pytorch>=1.10.0,<=1.12.1
  - torchvision>=0.8.1
  - cudatoolkit=11.3
  - torchmetrics<0.8.0
  - pytorch-lightning=1.4.5
  - tqdm
  - imageio
  - imageio-ffmpeg
  - pytest
