name: nnpf_gpu
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - jupyter
  - pytorch=1.6.0
  - torchvision>=0.7.0
  - cudatoolkit=10.2
  - pytorch-lightning=1.1.8
  - tqdm
  - imageio
  - imageio-ffmpeg
  - pytest
