name: nnpf_cpu
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - jupyter
  - pytorch>=1.7.0,<=1.12.1
  - torchvision>=0.8.1
  - cpuonly
  - torchmetrics=0.6.0
  - pytorch-lightning=1.4.5
  - tqdm
  - imageio
  - imageio-ffmpeg
  - pytest
